---
title: "The Promise and Perils of Packaging Your Processes"
subtitle: "⚔<br/>with xaringan"
author: "Karl Hailperin"
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---
# Who am I? (might move or drop this slide)

---
# What this talk is (and isn't) about
- Not (necessarily) about destined for Github/CRAN
- Not about how to build packages/intro to `devtools` and `roxygen2` (but there 
will be resources on that at the end)
- It's about practices I've found useful in developing packages for personal use 
or at work.

---
# Why should I bother building a package if no one else is going to use it?
- `devtools` and `usethis` provide tools for documenting what you were 
thinking when you wrote the code and what your dependencies are
- Future you will be grateful
- Low-stress way to develop related skills
- Good rule of thumb (that I can't find the source for): If you re-use the same 
code three times, write a function. If you re-use the same function three times,
write a package.

---
# How repeated code is like for loops (and therefore cupcakes)
- [For those unfamiliar with the above reference](https://www.youtube.com/watch?v=GyNqlOjhPCQ)
- Repeating code obscures changes.
- Repeating code leads to accidental changes.
- Need to remember to manually propigate changes to all versions.

---
# utils.R is your friend (internal functions)
- Remember that not everything needs to be `@exported`-ed
- moving chunks of code into a (well-named) internal function can make it easier
to review and test your code
- "Rule of three" applies to code within functions
- makes it easy to update a common workflow or use a parameter to 'switch' 
which workflow your using

---
# Using sensible defaults
- Use defaults to hide repeated processes that you don't always want to run.
- For me, this was driven home by a _very_ slow processing step I almost never 
used.
- often a simple TRUE/FALSE parameter is enough

---
# Case study in internal functions and defaults

---
# Additional resources
- [RStudio's cheetsheet](https://github.com/rstudio/cheatsheets/blob/master/package-development.pdf)
- [_R Packages_ by Hadley Wickham](http://r-pkgs.had.co.nz/)
- [WIP 2<sup>nd</sup> edition with Jenny Bryan](https://r-pkgs.org/)
- ["Writing an R package from scratch" by Hilary 
Parker](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/)
- [Thomas Westlake's version of "Writing an R package from scratch" using 
`usethis`](https://r-mageddon.netlify.com/post/writing-an-r-package-from-scratch/)
- ["R Package Primer" by Karl Broman](https://kbroman.org/pkg_primer/)
- ["`usethis` workflow for package development" by Emil 
Hvitfedlt](https://www.hvitfeldt.me/blog/usethis-workflow-for-package-development/)
- [The tidyverse style guide](https://style.tidyverse.org/)

---
# Thank you/questions
